fulll/actions

README.md
and remove reference to invoicing.app
=> Make instructions clear

deployment/.eslintrc, deployment/tools.js, lambdas/deployment/.eslintrc, lambdas/deployment/functions/authorize/index.js, lambdas/deployment/functions/confirm/index.js, lambdas/deployment/serverless.yml, lambdas/deployment/utils.js, lambdas/deployment/yarn.lock
crash if a cookie without a sign cookie
=> fix deploy lambda

create-pull-request/Dockerfile, create-pull-request/README.md, create-pull-request/action
=> Issue #21: Create pull request once pull request is merged

create-pull-request/action
=> Issue #21: Avoid PR not matching with defined HEAD

github-workflow/_tests/fixtures/action.hcl, github-workflow/printer/printer.go, github-workflow/printer/printer_test.go
Update test, fixtures, and then code
=> Add Runs argument for actions

release-button/Dockerfile
This also imply:
```shell
echo '#!/usr/bin/env node' | cat - index.js > deploy_button
chmod +x deploy_button
rm index.js
printf "\
node_modules
yarn.lock
" > .dockerignore
```
=> refactor: simplify Dockerfile

php-cs-fixer/README.md
See https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idsteps
=> doc: github action v2 examples

javascript/release-button/lib/deploy_button.js, javascript/release-button/package-lock.json, javascript/release-button/package.json, javascript/release-button/src/deploy_button.ts
=> Set output variable with result of deploy button

.github/workflows/publish-release-button.yml
=> Force push in publish workflow

.github/workflows/publish-release-button.yml, javascript/release-button/README.md
=> Add README.md to release-button

javascript/release-button/lib/deploy_button.js, javascript/release-button/src/deploy_button.ts
=> sign update not called

.github/workflows/publish-release-button.yml, javascript/release-button/yarn.lock
=> Fix release button workflow

php-cs-fixer/Dockerfile
update php version to make cs-fixer work with typed properties
=> update php version

php-cs-fixer/Dockerfile
https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/tag/v3.1.0
=> Bump to php-cs-fixer to 3.1

javascript/github-review/dist/index.js, javascript/github-review/src/index.js
issue : https://github.com/fulll/ISO-27001/issues/1099
=> fix github review action

javascript/github-review/dist/index.js, javascript/github-review/src/data_collector.js, javascript/github-review/src/github_tools.js, javascript/github-review/src/index.js
issue: https://github.com/fulll/ISO-27001/issues/1099
=> fix github review action v2

javascript/github-review/README.md, javascript/github-review/action.yml, javascript/github-review/dist/index.js, javascript/github-review/src/data_collector.js, javascript/github-review/src/github_tools.js, javascript/github-review/src/index.js, javascript/github-review/src/indicators_collector.js, javascript/github-review/src/queries.js, javascript/github-review/src/utils.js
Related to https://github.com/fulll/ISO-27001/issues/1099 and https://github.com/fulll/ISO-27001/issues/1392
=> Github Review Action : Add Indicators Review

javascript/github-review/dist/index.js, javascript/github-review/src/indicators_collector.js
Related to https://github.com/fulll/ISO-27001/issues/1392
=> Github review action: fix upload artifacts

javascript/github-review/src/data_collector.js, javascript/github-review/src/indicators_collector.js
related to https://github.com/fulll/ISO-27001/issues/1392
=> Fix: ISMS github action

javascript/github-review/dist/index.js, javascript/github-review/src/github_tools.js, javascript/github-review/src/indicators_collector.js
- add HR_INTERN indicators
- fixing indicators collect
related to https://github.com/fulll/ISO-27001/issues/1392
=> Github review action: fixing indicators collect

javascript/github-review/dist/index.js, javascript/github-review/src/analyser.js, javascript/github-review/src/data_collector.js, javascript/github-review/src/github_tools.js
https://github.com/fulll/ISO-27001/issues/1384
=> feat: add github direct rights review

javascript/github-review/dist/index.js, javascript/github-review/src/data_collector.js
https://github.com/fulll/ISO-27001/issues/1384
=> fix: remove unsed function for pr count

javascript/github-review/action.yml, javascript/github-review/dist/index.js, javascript/github-review/package.json, javascript/github-review/src/github_tools.js, javascript/github-review/src/index.js, javascript/github-review/src/indicators_collector.js, javascript/github-review/src/queries.js
Related to https://github.com/fulll/ISO-27001/issues/1732
=> Github Indicators Review : Fix indicators review (project v2)

javascript/release-button/lib/deploy_button.js, javascript/release-button/src/deploy_button.ts
We need to add a new environment called _Beta_ for the release button. This environment will be use in ibiza-code.
related to : https://github.com/fulll/chapter-secops/issues/261
=> release button: add new env (beta)

.github/workflows/test-workflow-call.yml
issue: https://github.com/fulll/chapter-secops/issues/264
=> poc reusable workflow

.github/workflows/create-deployment-release-workflow.yml, .github/workflows/create-deployment-workflow.yml, .github/workflows/update-deployment-workflow.yml
issue: https://github.com/fulll/chapter-secops/issues/264
=> Add reusable workflows

.github/workflows/README.md, .github/workflows/update-deployment-on-failure-workflow.yml, .github/workflows/update-deployment-on-success-workflow.yml
This is a proposal in order to be more explicit.
=> enhancement: rename deployments steps

.github/workflows/update-deployment-on-failure-workflow.yml
=> feat fulll/chapter-architect#154: run failure job only on failure

.github/workflows/update-deployment-workflow.yml
=> feat fulll/chapter-architect#154: fix indentation

.github/workflows/README.md, .github/workflows/automatic-master-dev-pr.yml
=> feat fulll/chapter-architect#154: add appropriate token for PR validation

.github/workflows/create-deployment-release-workflow.yml
Add missing `-json body --jq '.body'`
=> feat fulll/chapter-architect#154: fix release note update

.github/workflows/create-deployment-release-workflow.yml
Linked to ulll/chapter-architect#154
=> feat fulll/chapter-architect#154: fix release note edition

.github/workflows/README.md, .github/workflows/prepare-prod-deployment-workflow.yml, .github/workflows/update-deployment-workflow.yml
See: https://github.com/fulll/purchase.api/actions/runs/4161098227/jobs/7198708322
=> fix fulll/chapter-architect#154: repository variable usage

.github/workflows/README.md, .github/workflows/update-deployment-workflow.yml
- fix update deployment workflow
- update readme
=> feat fulll/chapter-architect#154: fix update deployment workflow

.github/workflows/create-deployment-release-workflow.yml, .github/workflows/create-deployment-workflow.yml, .github/workflows/update-deployment-workflow.yml
=> feat fulll/chapter-architect#154: add missing checkout on deployment status update

.github/workflows/README.md, .github/workflows/update-deployment-workflow.yml
issue: https://github.com/fulll/chapter-architect/issues/154
=> ci/cd: add on_failure input for update-deployment

.github/workflows/automatic-master-dev-pr.yml
=> feat fulll/chapter-architect#154: Update Github Action automatic PR by checking if PR already exists

.github/workflows/README.md, .github/workflows/automatic-master-dev-pr.yml, .github/workflows/automatic-pr-workflow.yml
Add condition to disable auto merge
Thanks @DorianBonhomme for the idea 😄 
=> feat fulll/chapter-architect#154: add condition for auto_merge
